author:
  bunker_url: bunker://<hex>?relay=ws://127.0.0.1:<secret-code>
  npub: npub1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

budget:
  daily_limit: 1000 # sats per day
  per_npub_limit: 100 # sats per user per day

database:
  path: ./zapbot.db

nwc_url: nostr+walletconnect://<wallet_pubkey>?relay=wss%3A%2F%2Frelay.example.com%2Fv1&secret=<secret>&lud16=user%40domain.com

reaction:
  enabled: true
  content: ":catJAM:"
  emoji_name: catJAM
  emoji_url: https://cdn.betterttv.net/emote/5f1b0186cf6d2144653d2970/3x.webp

relays:
  - wss://relay.damus.io
  - wss://nos.lol
  - wss://relay.nostr.band

selected_list: 4f519a14-d650-43a1-9ee3-37d8282d6142

zap:
  amount: 5 # sats per zap
  comment: "keep posting"
