services:
  pekka:
    build: .
    container_name: pekka
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./config.yml:/app/config.yml
      - ./pekka.db:/app/pekka.db
    restart: unless-stopped
    command: tail -f /dev/null